### ISSUE TITLE
Unable to connect to server Issue

### ISSUE THREAD

**Issue by Smolboydotjpeg** [pierre-josselin/payday-2-ultimate-trainer-6#84]
PAYDAY 2 - Ultimate Trainer 6
--- TEST ---
You must close this window before using the mod!
Checking Node.js version... OK
Checking installation status... OK
Testing application web server... OK
Testing server... OK
All tests passed!
You can now close this window.    

I have done everything properly and I can not connect to the server when I click on the ultimate trainer in game.

**Comment by pierre-josselin** [comment]
Hi, some people have the same problem but I cant figure what is wrong, if you are ok for a remote access session with [Teamviewer](https://www.teamviewer.com/fr/) add me on Discord: fiddlesucks. I might be able to get more information myself.

**Comment by pierre-josselin** [comment]
Otherwise I suggest the following test:

- Close the game and any console already open
- Navigate inside the `payday-2-ultimate-trainer-6-main` directory
- From this directory, press ALT + F
- Click on "Open PowerShell"
- Paste the command `node .\payday-2-ultimate-trainer-6-server\src\index.js` and press ENTER
- While keeping the first console open, open another one
- Paste the command `node node_modules\http-server\bin\http-server --port 1140 --proxy "http://127.0.0.1:1140?" payday-2-ultimate-trainer-6-app\dist` and press ENTER
- Run the game, try to access application and see if there any message in the PowerShell consoles

**Comment by pierre-josselin** [comment]
With the help of @airblizzard, we was able to identify the issue. The server does not run automatically for some (Windows 11?) users.

A simple and good fix we found is to create an empty text file named developer inside the mods folder.
